// Pure helpers: profile-file parsing/serialization and the Lua translation
// hyprland.lua actually understands. No QML dependencies, so this stays easy
// to reason about (and reuse) on its own.
//
// A monitor object looks like:
//   { name, enabled, width, height, refresh, x, y, scale, transform }
// transform: 0/1/2/3 (0 = normal, 1 = 90°, 2 = 180°, 3 = 270°), same
// encoding Hyprland's own `transform` keyword uses.

function defaultMonitor(name) {
  return {
    name: name || "",
    enabled: true,
    width: 1920,
    height: 1080,
    refresh: 60,
    x: 0,
    y: 0,
    scale: 1.0,
    transform: 0
  }
}

// ---- profiles/*.conf (this plugin's own storage format) ------------------

function parseProfileLine(line) {
  var trimmed = String(line || "").trim()
  if (!trimmed || trimmed.indexOf("monitor") !== 0) return null

  var parts = trimmed.split(",").map(function(s) { return s.trim() })
  if (parts.length < 2) return null

  var nameParts = parts[0].split("=").map(function(s) { return s.trim() })
  if (nameParts.length < 2) return null
  var name = nameParts[1]

  if (parts[1] === "disable") {
    var disabled = defaultMonitor(name)
    disabled.enabled = false
    return disabled
  }

  var resParts = parts[1].split("@")
  var res = resParts[0].split("x")
  if (res.length < 2) return null
  var width = parseInt(res[0], 10)
  var height = parseInt(res[1], 10)
  var refresh = resParts.length > 1 ? parseFloat(resParts[1]) : 60

  var pos = (parts[2] || "0x0").split("x")
  var x = parseInt(pos[0], 10) || 0
  var y = parseInt(pos[1], 10) || 0

  var scale = parts.length > 3 ? parseFloat(parts[3]) : 1.0

  var transform = 0
  if (parts.length > 5 && parts[4] === "transform") transform = parseInt(parts[5], 10) || 0

  if (!isFinite(width) || !isFinite(height)) return null

  return { name: name, enabled: true, width: width, height: height, refresh: refresh, x: x, y: y, scale: scale, transform: transform }
}

function parseProfileText(text) {
  var lines = String(text || "").split("\n")
  var monitors = []
  for (var i = 0; i < lines.length; i++) {
    var m = parseProfileLine(lines[i])
    if (m) monitors.push(m)
  }
  return monitors
}

function monitorToProfileLine(m) {
  if (!m.enabled) return "monitor = " + m.name + ", disable"
  var line = "monitor = " + m.name + ", " + m.width + "x" + m.height + "@" + m.refresh + ", " + m.x + "x" + m.y + ", " + m.scale
  if (m.transform) line += ", transform, " + m.transform
  return line
}

function profileToText(monitors) {
  return monitors.map(monitorToProfileLine).join("\n") + "\n"
}

// ---- hypr_screen.lua (what hyprland.lua actually requires and applies) ----

function monitorToLua(m) {
  if (!m.enabled) return "hl.monitor({ output = \"" + m.name + "\", disabled = true })"
  var line = "hl.monitor({ output = \"" + m.name + "\", mode = \"" + m.width + "x" + m.height + "@" + m.refresh + "\", " +
    "position = \"" + m.x + "x" + m.y + "\", scale = " + m.scale
  if (m.transform) line += ", transform = " + m.transform
  line += " })"
  return line
}

function profileToLua(monitors, profileName) {
  var lines = [
    "-- Generated by the Monitor Profiles plugin. Do not edit by hand;",
    "-- changes are overwritten the next time a profile is applied.",
    "-- Active profile: " + (profileName || "")
  ]
  monitors.forEach(function(m) { lines.push(monitorToLua(m)) })
  return lines.join("\n") + "\n"
}

// ---- live `hyprctl monitors -j` -> the same monitor shape ----------------

function monitorFromHyprctlJson(j) {
  return {
    name: j.name,
    enabled: !j.disabled,
    width: j.width,
    height: j.height,
    refresh: Math.round((j.refreshRate || 60) * 100) / 100,
    x: j.x,
    y: j.y,
    scale: Math.round((j.scale || 1) * 100) / 100,
    transform: j.transform || 0
  }
}
